### ISSUE TITLE
Electron not included

### ISSUE THREAD

**Issue by williamluke4** [atto-byte/pagedraw#1]
Electron Versions < 2 will fail
Issue: https://github.com/electron/electron/issues/13984

**Comment by williamluke4** [comment]
Update Electron Globally
```npm install -g electron```

**Comment by harkal18** [comment]
i tried npm install -g electron@latest but even then it didn't work
so i manually updated files in my global node_modules from that electron sample project node_modules folder and it worked

i mean i replaced C:\Users\user\node_modules\electron with C:\Users\user\electronProjects\electron-quick-start\node_modules\electron and it worked ;)
